//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosDinero
    {
        public int id_deposito { get; set; }
        public string nombre_deposito { get; set; }
        public string CVU_deposito { get; set; }
        public string nro_tarjeta { get; set; }
        public Nullable<System.DateTime> fecha_venc { get; set; }
        public Nullable<int> cod_seguridad { get; set; }
        public string nombre_titular { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
