//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inversiones
    {
        public int id_inversion { get; set; }
        public decimal monto_inversion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string CVU_inversion { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
