//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosServicio
    {
        public int nro_comprobante { get; set; }
        public int id_servicio { get; set; }
        public string CVU_pago { get; set; }
        public int nro_factura { get; set; }
        public string nombre_factura { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
